version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file: 
      - credentials.env
    ports:
      - "4500:5432"
    volumes:
      - ./database/tables:/docker-entrypoint-initdb.d

  fastapi_app:
    build:
      context: ./app/.
      dockerfile: Dockerfile
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: 
      - credentials.env
    command: uvicorn api.main:app --host 0.0.0.0 --reload
